name: Fully Automated Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Clean and Build project
        run: |
          rm -rf build 
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Sync built files to S3
        run: aws s3 sync ./build s3://event-app-artifacts-vishwasritech --delete

      # --- SECURE DEPLOYMENT VIA AWS SSM ---
      - name: Deploy Frontend to EC2 via SSM
        run: |
          echo "--- Sending SSM Command for Frontend ---"
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "echo --- 1. Creating directory (if not exist) ---",
              "sudo mkdir -p /var/www/sparkfest",
              "echo --- 2. Pulling frontend from S3 ---",
              "sudo aws s3 sync s3://event-app-artifacts-vishwasritech /var/www/sparkfest/ --delete",
              "echo --- 3. Setting Nginx permissions ---",
              "sudo chown -R nginx:nginx /var/www/sparkfest",
              "echo --- Frontend deploy complete ---"
            ]'
