name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- Setup Steps ---
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use the Node version appropriate for your project

      - name: Install dependencies
        run: npm install

      # --- CRITICAL FIX: Clean and Build Project ---
      # This step ensures the 'build' folder is deleted before a new build,
      # forcing create-react-app to generate a fresh index.html with the correct asset links.
      - name: Clean and Build project
        run: |
          rm -rf build 
          npm run build
      # -----------------------------------------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Sync built files to S3
        run: |
          # This command synchronizes the new build contents to the S3 bucket,
          # including the freshly generated index.html.
          aws s3 sync ./build s3://event-app-artifacts-vishwasritech --delete
